config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
  resources :plays do
    resources :reviews
  end

  root 'plays#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :plays
end

app/models/play.rb
class Play < ApplicationRecord
  belongs_to :user
  belongs_to :category
  has_many   :reviews

  has_one_attached :pic
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :play
end

app/models/user.rb
class User < ApplicationRecord
  has_many :plays
  has_many :reviews
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/plays_controller.rb
class PlaysController < ApplicationController
  before_action :find_play, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:new, :edit]

  def index
    if params[:category].blank?
      @plays = Play.all.order("created_at DESC")
    else
      @category_id = Category.find_by(name: params[:category]).id
      @plays = Play.where(:category_id => @category_id).order("created_at DESC")
    end
  end

  def show
    if @play.reviews.blank?
      @average_review = 0
    else
      @average_review = @play.reviews.average(:rating).round(2)
    end
  end

  def new
    @play = current_user.plays.build
    @categories = Category.all.map{ |c| [c.name, c.id] }
  end

  def create
    @play = current_user.plays.build(play_params)
    @play.category_id = params[:category_id]

    if @play.save
      redirect_to root_path
    else
      render 'new'
    end

  end

  def edit
    @categories = Category.all.map{ |c| [c.name, c.id] }
  end

  def update
    @play.category_id = params[:category_id]

    if @play.update(play_params)
      redirect_to play_path(@play)
    else
      render 'edit'
    end

  end

  def destroy
    @play.destroy
    redirect_to root_path
  end

  private

  def play_params
    params.require(:play).permit(:title, :description, :director, :category_id, :pic)
  end

  def find_play
    @play = Play.find(params[:id])
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :find_play
  before_action :find_review, only: [:edit, :update, :destroy]
  before_action :authenticate_user!, only: [:new, :edit]
  
  def new
    @review = Review.new
  end

  
  def create
    @review = Review.new(review_params)
    @review.play_id = @play.id
    @review.user_id = current_user.id

    if @review.save
      redirect_to play_path(@play)
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @review.update(review_params)
      redirect_to play_path(@play)
    else
      render 'edit'
    end
  end

  def destroy
    @review.destroy
    redirect_to play_path(@play)
  end

  private

    def find_play
      @play = Play.find(params[:play_id])
    end

    def find_review
      @review = Review.find(params[:id])
    end

    def review_params
      params.require(:review).permit(:rating, :comment)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/plays_helper.rb
module PlaysHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Broadway</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag "application", "data-turbo-track": "reload" %>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  </head>

  <body>
      <nav class="bg-gray-800 shadow-lg mt-2">
        <div class="container mx-auto">
          <div class="sm:flex justify-between">
            <%= link_to "Broadway", root_path,  class: "text-pink-300 text-2xl p-3 " %>
            <% if user_signed_in? %>
            <div class="dropdown inline-block relative mt-12.95l sm:self-center">
              <button class="border-2 border-pink-300 hover:border-pink-700 text-pink-300 text-xl py-2 px-4 rounded inline-flex items-center" id="toggle">
                <span class="mr-1">Dropdown</span>
                <svg class="fill-current h-4 w-4" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"><path d="M9.293 12.95l.707.707L15.657 8l-1.414-1.414L10 10.828 5.757 6.586 4.343 8z"/> </svg>
              </button>
              <ul class="dropdown-menu z-40 absolute hidden text-pink-700 pt-1" id="dropdown">
                <% Category.all.each do |category| %>
                  <li id="category">
                    <%= link_to category.name, plays_path(category: category.name),
                        class: "rounded-t bg-gray-200 hover:bg-pink-400 py-2 px-4 block whitespace-no-wrap"
                    %> 
                  </li>
                <% end %>
              </ul>
            </div>
            <ul class="text-pink-300 sm:self-center text-xl border-t sm:border-none">
                <li class="sm:inline-block">
                  <%= link_to "New Play", new_play_path, class: "p-3 hover:text-white" %>
                </li>
              <% end %>
              <% if current_user.present?%>
                <li class="sm:inline-block">
                  <%= link_to "Sing Out", destroy_user_session_path, method: :delete, class: "p-3 hover:text-white" %>
                </li>
              <% else %>
                <li class="sm:inline-block">
                  <%= link_to "Log In", new_user_session_path, class: "p-3 hover:text-white" %>
                </li>
                <li class="sm:inline-block">
                  <%= link_to "Sing Up", new_user_registration_path, class: "p-3 hover:text-white" %>
                </li>
              <% end %>
            </ul>
          </div>
        </div>
      </nav>
    <div class="container mx-auto">
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
      <%= yield %>
    </div>
    <%= javascript_pack_tag 'custom', 'data-turbolinks-track': 'reload' %>
  </body>

</html>

app/views/plays/_form.html.erb
<%= simple_form_for @play do |f| %>
  <%= select_tag(:category_id, options_for_select(@categories), :prompt => "Select Category")%>
  <%= f.input :title, label: "Play Title",
              label_html: { class: "uppercase tracking-wide text-black text-xs font-bold mb-2"}, 
              input_html: { autocomplete: "title", 
                            class: "w-full bg-gray-200 text-black border border-gray-200 rounded py-3 px-4 mb-3" } 
  %>
  <%= f.input :description,
              label_html: { class: "uppercase tracking-wide text-black text-xs font-bold mb-2"}, 
              input_html: { autocomplete: "description", 
                            class: "w-full h-40 bg-gray-200 text-black border border-gray-200 rounded py-3 px-4 mb-3" } 
  %>
  <%= f.input :director, label: "Director",
              label_html: { class: "uppercase tracking-wide text-black text-xs font-bold mb-2"}, 
              input_html: { autocomplete: "title", 
                            class: "w-full bg-gray-200 text-black border border-gray-200 rounded py-3 px-4 mb-3" } 
  %>

  <% if @play.pic.attached? %>
    <%= image_tag @play.pic, style: "width: 200px; display: block "%>
  <% end %>
  <%= f.input :pic, as: :file, :label => 'Your image ', input_html: { class: 'bg-gray-200 text-black border border-gray-200 rounded py-3 px-4 mb-3'} %>

  <%= f.button :submit, class: "bg-pink-400 hover:bg-pink-500 text-white uppercase text-s mx-auto p-2 rounded m-2" %>
<% end %>

app/views/plays/edit.html.erb
<div class="mt-4">
<div class="">
  <h1 class="text-pink-400 text-2xl ">Edit Broadway Play</h1>
</div>
<div class="container mx-auto">
  <%= simple_form_for @play, html: { multipart: true } do |f| %>
  <%= f.select :category_id, @categories %>
  <%= f.input :title, label: "Play Title",
              label_html: { class: "uppercase tracking-wide text-black text-xs font-bold mb-2"}, 
              input_html: { autocomplete: "title", 
                            class: "w-full bg-gray-200 text-black border border-gray-200 rounded py-3 px-4 mb-3" } 
  %>
  <%= f.input :description,
              label_html: { class: "uppercase tracking-wide text-black text-xs font-bold mb-2"}, 
              input_html: { autocomplete: "description", 
                            class: "w-full h-40 bg-gray-200 text-black border border-gray-200 rounded py-3 px-4 mb-3" } 
  %>
  <%= f.input :director, label: "Director",
              label_html: { class: "uppercase tracking-wide text-black text-xs font-bold mb-2"}, 
              input_html: { autocomplete: "title", 
                            class: "w-full bg-gray-200 text-black border border-gray-200 rounded py-3 px-4 mb-3" } 
  %>
  <% if @play.pic.attached? %>
    <%= image_tag @play.pic, style: "width: 200px; display: block "%>
  <% end %>
  <%= f.input :pic, as: :file, :label => 'Your image ', input_html: { class: 'bg-gray-200 text-black border border-gray-200 rounded py-3 px-4 mb-3'} %>
  <%= f.button :submit, class: "bg-pink-400 hover:bg-pink-500 text-white uppercase text-s mx-auto p-2 rounded m-2" %>
<% end %>
</div>
</div>

app/views/plays/index.html.erb
<div>
  <% if params[:category] %>
    <h1 class="font-bold mt-12 pb-2 text-2xl border-b border-gray-200"><%= params[:category]%></h1>
  <% else %>
    <h1 class="font-bold mt-12 pb-2 text-2xl border-b border-gray-200">Now Playing!</h1>
  <% end %>
  <% if @plays.count == 0 %>
    <h3 class="">There are no plays in this category!</h3>
  <% else %>
    <div class="mt-8 grid md:grid-cols-4 gap-10">
      <!-- Card go here -->
        <% @plays.each do |play| %>
          <div class="bg-white rounded shadow-md relative hover:shadow-lg">
            <% if play.pic.attached? %> 
              <%= image_tag play.pic, class: "w-full"%>
            <% end %>
            <div class="m-4">
              <h2 class="font-bold"><%= link_to play.title, play_path(play) %></h2>
            </div>
          </div>
        <% end %>
    </div>
  <% end %>
</div>

app/views/plays/new.html.erb
<div class="mt-4">
<div class="">
  <h1 class="text-pink-400 text-2xl ">New Broadway Play</h1>
</div>
<div class="container mx-auto">
  <%= render 'form' %>
</div>
</div>

app/views/plays/show.html.erb
<div class="grid md:grid-cols-12 mt-4">
  <div class="md:col-span-4 mt-4">
    <% if @play.pic.attached? %> 
      <%= image_tag @play.pic, style: "width:325px;  height: 450px"%>
    <% end %>
    <div class="m-4">
      <h2 class="font-bold"><%= @play.title %></h2>
    </div>
  </div>
  <div class="md:col-span-8 border-2 border-pink-300 rounded p-4">
    <h1 class="text-pink-300 text-3xl"><%= @play.title %></h1>
    <h3 class="text-2xl"><span>From - </span><%= @play.director %></h3>
    <h4 clsss="text-blue-200 bold text-l"><%= @play.category.name %></h3>
    
    <h4 clsss="text-blue-200 bold text-l">Average Rating!</h3>
    <div>
        <% if @average_review.ceil == 5 %> 
          <span class="fa fa-star checked"></span>
          <span class="fa fa-star checked"></span>
          <span class="fa fa-star checked"></span>
          <span class="fa fa-star checked"></span>
          <span class="fa fa-star checked"></span>
        <% elsif @average_review.ceil == 4%>
          <span class="fa fa-star checked"></span>
          <span class="fa fa-star checked"></span>
          <span class="fa fa-star checked"></span>
          <span class="fa fa-star checked"></span>
          <span class="fa fa-star "></span>
        <% elsif @average_review.ceil == 3%>
          <span class="fa fa-star checked"></span>
          <span class="fa fa-star checked"></span>
          <span class="fa fa-star checked"></span>
          <span class="fa fa-star "></span>
          <span class="fa fa-star "></span>
        <% elsif @average_review.ceil == 2%>
          <span class="fa fa-star checked"></span>
          <span class="fa fa-star checked"></span>
          <span class="fa fa-star "></span>
          <span class="fa fa-star "></span>
          <span class="fa fa-star "></span>
        <% elsif @average_review.ceil == 1%>
          <span class="fa fa-star checked"></span>
          <span class="fa fa-star "></span>
          <span class="fa fa-star "></span>
          <span class="fa fa-star "></span>
          <span class="fa fa-star "></span>
        <% else %>
          <span class="fa fa-star "></span>
          <span class="fa fa-star "></span>
          <span class="fa fa-star "></span>
          <span class="fa fa-star "></span>
          <span class="fa fa-star "></span>
          <% end %>
    </div>
    <p><%= @play.description %></p>
    <div class="mt-2">
      <% if user_signed_in? %>
        <% if @play.user_id == current_user.id %>
          <%= link_to "Back", root_path,
              class: "border-2 
                border-indigo-400 
                hover:border-indigo-500 
                text-gray-700 
                hover:text-indigo-800
                hover:bg-indigo-500 
                text-sm 
                uppercase 
                p-2 
                flex-initial
                rounded 
                "            
           %>
          <%= link_to "Edit", edit_play_path(@play),
              class: "border-2 
                    border-blue-400 
                    hover:border-blue-500 
                    text-gray-700 
                    hover:text-blue-800
                    hover:bg-blue-500 
                    text-sm 
                    uppercase 
                    p-2 
                    rounded 
                    ml-2"
          %>
          <%= link_to "Delete", play_path(@play), method: :delete,
              data: { confirm: "Are you sure?"},
              class: "border-2 
                        border-pink-400 
                        hover:border-pink-500 
                        text-gray-700 
                        hover:text-pink-800
                        hover:bg-pink-500 
                        text-sm 
                        uppercase 
                        p-2 
                        flex-initial
                        rounded 
                        ml-2"    
          %>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

<div class="grid md:grid-cols-12 mt-4">
  <div class="md:col-span-10">
    <h1>Reviews</h1>
    <%= render @play.reviews %>
    <div class="mt-4">
      <%= link_to "Add Review", 
          new_play_review_path(@play), 
          class: "border-2 
                border-indigo-400 
                hover:border-indigo-500 
                text-gray-700 
                hover:text-indigo-800
                hover:bg-indigo-500 
                text-sm 
                uppercase 
                p-2 
                flex-initial
                rounded 
                "
      %>
    </div>
  </div>
</div>

app/views/reviews/_form.html.erb
<%= simple_form_for([@play, @play.reviews.build]) do |f| %>
  <div>
    <%= f.input :rating, as: :integer,  label: "Rating",
            label_html: { class: "uppercase tracking-wide text-black text-xs font-bold mb-2"}, 
            input_html: { class: "w-full bg-gray-200 text-black border border-gray-200 rounded py-3 px-4 mb-3",
                          min: '0',
                          max: '5',
             } 
    %>
  </div>
    <%= f.input :comment, label: "Comment",
            label_html: { class: "uppercase tracking-wide text-black text-xs font-bold mb-2"}, 
            input_html: { autocomplete: "Comment",
                           
                          class: "w-full h-40 bg-gray-200 text-black border border-gray-200 rounded py-3 px-4 mb-3" } %>

    <%= f.button :submit, class: "bg-pink-400 
                                  hover:bg-pink-500 
                                  text-white 
                                  uppercase 
                                  text-s 
                                  mx-auto 
                                  p-2 rounded m-2"
    %>

<% end %>

app/views/reviews/_review.html.erb
<div>
  <div class="mt-2">
    <% if review.rating == 5 %> 
        <span class="fa fa-star checked"></span>
        <span class="fa fa-star checked"></span>
        <span class="fa fa-star checked"></span>
        <span class="fa fa-star checked"></span>
        <span class="fa fa-star checked"></span>
    <% elsif review.rating == 4%>
        <span class="fa fa-star checked"></span>
        <span class="fa fa-star checked"></span>
        <span class="fa fa-star checked"></span>
        <span class="fa fa-star checked"></span>
        <span class="fa fa-star "></span>
    <% elsif review.rating == 3%>
        <span class="fa fa-star checked"></span>
        <span class="fa fa-star checked"></span>
        <span class="fa fa-star checked"></span>
        <span class="fa fa-star "></span>
        <span class="fa fa-star "></span>
    <% elsif review.rating == 2%>
        <span class="fa fa-star checked"></span>
        <span class="fa fa-star checked"></span>
        <span class="fa fa-star "></span>
        <span class="fa fa-star "></span>
        <span class="fa fa-star "></span>
    <% elsif review.rating == 1%>
        <span class="fa fa-star checked"></span>
        <span class="fa fa-star "></span>
        <span class="fa fa-star "></span>
        <span class="fa fa-star "></span>
        <span class="fa fa-star "></span>
    <% else %>
        <span class="fa fa-star "></span>
        <span class="fa fa-star "></span>
        <span class="fa fa-star "></span>
        <span class="fa fa-star "></span>
        <span class="fa fa-star "></span>
    <% end%>
    <p><%= review.comment %></p>
  </div>
  <% if user_signed_in? %>
    <% if review.user_id == current_user.id %>
      <div class="mt-2">
        <%= link_to "Edit", edit_play_review_path(review.play, review), 
            class: "border-2 
                    border-blue-400 
                    hover:border-blue-500 
                    text-gray-700 
                    hover:text-blue-800
                    hover:bg-blue-500 
                    text-sm 
                    uppercase 
                    p-2 
                    rounded 
                    ml-2" %>
        <%= link_to "Delete", play_review_path(review.play, review), method: :delete, 
            data: { confirm: "Are you sure?" }, 
            class: "border-2 
                        border-pink-400 
                        hover:border-pink-500 
                        text-gray-700 
                        hover:text-pink-800
                        hover:bg-pink-500 
                        text-sm 
                        uppercase 
                        p-2 
                        flex-initial
                        rounded 
                        ml-2"     %>
      </div>
    <% end %>
  <% end%>
  <div class = "border-b-2 border-pink-300 mt-4 shadow"></div>
</div>

app/views/reviews/edit.html.erb
<div class="mt-4">
  <div>
    <h1 class="text-pink-300 text-xl">Edit Review</h1>
    <%= simple_form_for([@play, @review]) do |f| %>
      <div>
        <%= f.input :rating, label: "Rating",
                label_html: { class: "uppercase tracking-wide text-black text-xs font-bold mb-2"}, 
                input_html: { class: "w-full bg-gray-200 text-black border border-gray-200 rounded py-3 px-4 mb-3",
                              min: '0',
                              max: '5',
                } 
        %>
      </div>
        <%= f.input :comment, label: "Comment",
                label_html: { class: "uppercase tracking-wide text-black text-xs font-bold mb-2"}, 
                input_html: { autocomplete: "Comment", 
                              class: "w-full h-40 bg-gray-200 text-black border border-gray-200 rounded py-3 px-4 mb-3" } %>

        <%= f.button :submit, class: "bg-pink-400 
                                      hover:bg-pink-500 
                                      text-white 
                                      uppercase 
                                      text-s 
                                      mx-auto 
                                      p-2 rounded m-2"
        %>

      <% end %>
  </div>
</div>

app/views/reviews/new.html.erb
<div>
  <div>
    <h1 class="text-pink-300 text-xl">Post Review</h1>
    <%= render 'form' %>
  </div>
</div>